require("settings")
require("mappings")
require("packer-config")

require("plugins/dashboard")
require("plugins/nvimtree")
require("plugins/lualine")
require("plugins/bufferline")
require("plugins/indentblankline")
require("plugins/lsp")
require("plugins/lspkind")
